### ISSUE TITLE
Cannot run swift simulator

### ISSUE THREAD

**Issue by SantiDiazC** [jhavl/dkt#5]
Hi,
Thanks for your great work. 
I set my conda environment as in the documentation and installed all the required packages, 
however, when trying to run the simulator (for example the `notebook 4: Numerical Inverse Kinematics`) or just a simple demo script:

```python
import roboticstoolbox as rp

panda = rp.models.Panda()
panda.plot(q=panda.qr)
```
this error appears:
``` error
Exception in thread Thread-5 (SwiftSocket):
Traceback (most recent call last):
  File "/home/hri-david/anaconda3/envs/dktutorial/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/hri-david/anaconda3/envs/dktutorial/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
  File "/home/hri-david/anaconda3/envs/dktutorial/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hri-david/anaconda3/envs/dktutorial/lib/python3.10/site-packages/swift/SwiftRoute.py", line 296, in __init__
    start_server = websockets.serve(self.serve, "localhost", port)
  File "/home/hri-david/anaconda3/envs/dktutorial/lib/python3.10/site-packages/websockets/asyncio/server.py", line 737, in __init__
    self.server = Server(
  File "/home/hri-david/anaconda3/envs/dktutorial/lib/python3.10/site-packages/websockets/asyncio/server.py", line 281, in __init__
    self.loop = asyncio.get_running_loop()
RuntimeError: no running event loop
```
Is there any solution to this? 

Thank you in advance!

**Comment by SantiDiazC** [comment]
I found a solution, there is a problem with the websockets package version for python 3.10. 
So the solution was to downgrade my python version to 3.9 and to install a compatible websockets version:
```
pip install websockets==9.1
```
I hope it helps for someone experiencing the same issue.

**Comment by yaskawaglobal** [comment]
I ran your suggested pip command and it did solve the "no event loop running" issue.  (I didn't downgrade Python to 3.9 from 3.10 though).  However, now, after `visualise_ik(solver, env)` I see an interactive 3D view inline, but only axes show and there is an exception and message "Could not connect to the Swift simulator".
Is that view the simulator?  Should it have opened in another tab or something? (or was I supposed to independently start Swift somehow?)
